- profiles/ug/themes/ug/ug_theme/templates/node.tpl.php
Fixes issue #272 
Overwrites node.tpl.php in the template file. Adds an if statement to check if the title variable contains text. If not, then hides the link.
> Hide link if no title available in full page node

- profiles/ug/themes/ug/ug_cornerstone/templates/includes/ug-header.inc
Moved the menu expand/collapse button after the "brand" (U of G logo)
in the global (red) navbar menu. Previously the button was before
the brand in document order (as it is in the Bootstrap navbar
documentation). This looks okay, but it means that when you navigating
with the keyboard the "new" menu items that are added when you click
the expand button do not immediately follow the button (in document
order) which violates WCAG SCR26
(http://www.w3.org/TR/2014/NOTE-WCAG20-TECHS-20140916/SCR26.html)
The new ordering looks the same but is more accessible.
Fixes issue #125.
> Move navbar button after brand in global navbar.

- profiles/ug/modules/ug/ug_migrate_d7/migrate_settings_d7.php
- profiles/ug/modules/ug/ug_migrate_d7/ug_migrate_d7.migrate.inc
- profiles/ug/modules/ug/ug_migrate_d7/ug_migrate_d7_node.inc
- sites/all/modules/field_collection/field_collection.module
Adds file attachment migration class. I've tested this on Business and Biophysics using the following procedure:
1. Move over the files manually to the /files directory under the site directory
2. drush mi UGFile7
3. drush mi --update UGPage7
4. drush mi --update UGNews7
Note: Includes patch on Field Collection to avoid deleting field collections if they do not exist.
**Update:** Fixes #336 by making the node migrations dependent on the file migration.
> (Migrate D7) Add File migration class + file attachment migration for Page, News, Events

- profiles/ug/themes/ug/ug_cornerstone/css/style.css
I've added a fallback color to `#ug-header` background to prevent contrast issues if the background image fails to load. I've also added `color: #FEFEFE;` (white) because the existing font color for `#ug-header` was `#333` (black). This was tripping the WAVE tool into giving us another contrast issue - black text on red background.
> Fix: Prevents low-contrast text if #ug-header background image fails to load (UG Header)[refs #286]

- profiles/ug/modules/ug/ug_migrate_d6/migrate_settings_d6.php
- profiles/ug/modules/ug/ug_migrate_d6/ug_migrate_d6.migrate.inc
- profiles/ug/modules/ug/ug_migrate_d6/ug_migrate_d6_node.inc
Implements FAQ, FAQ category and FAQ keyword migration from Drupal 6 to Drupal 7 sites.
Works well on local machine migration. Recommend testing migration using data from CIO.
Fixes #358
> New: Add FAQ, FAQ category/keyword migration (UG Migrate D6)[fixes #358]

- profiles/ug/modules/ug/ug_migrate_d6/migrate_settings_d6.php
- profiles/ug/modules/ug/ug_migrate_d6/ug_migrate_d6.migrate.inc
- profiles/ug/modules/ug/ug_migrate_d6/ug_migrate_d6_node.inc
Add file attachment field migrations to Page, News, and Events migrations for D6. 
Tested successfully on local machine.
At the moment, I'm not seeing any D6 to D7 sites with file attachments, so testing will be limited to whether UGFile6 successfully brings over the files. By default, I am pulling in the files from the upload table, however, if you find that files are not coming through, check to see if you need to reference a different source table for the attachments.
> (Migrate D6) Add File migration class + file attachment migration for Page, News, Events

- profiles/ug/modules/ug/ug_migrate_d6/migrate_settings_d6.php
- profiles/ug/modules/ug/ug_migrate_d6/ug_migrate_d6.migrate.inc
- profiles/ug/modules/ug/ug_migrate_d6/ug_migrate_d6_node.inc
Adds UGImage6 class (specifically migrates items from the Image and Image Attach module and connects them up with any nodes that reference them). Relies on File migration class introduced in https://github.com/ccswbs/hjckrrh/pull/344
Connects those migrated images with News and Events.
Tested successfully on local machine. Needs a real-data migration test on one of the D6 sites.
> (Migrate D6) Add Feature Image migration to News, Event

- profiles/ug/modules/ug/ug_migrate_d6/migrate_settings_d6.php
- profiles/ug/modules/ug/ug_migrate_d6/ug_migrate_d6_node.inc
Migrates a single image assist tag into the Page body field. Src url is likely going to be /sites/uoguelph.ca.sitename/files, however, if you find that the images can only be found at /sitename/uoguelph.ca.sitename/files, use ```source_page_image_src_prefix``` value to hold the ```/sitename``` prefix.
*Note:* Code still needs to be adapted so multiple image_assist tags are replaced by an <img> HTML tag (see https://github.com/ccswbs/hjckrrh/issues/373 for details).
> New: Migrate image (img_assist) into Page body (UG Migrate D6)

- profiles/ug/themes/ug/ug_theme/template.php
Fixes #191 
theme_file_icon was overridden in ug_theme to provide file icon
alt text. This has since been fixed in Drupal core
(see: https://www.drupal.org/node/2163209).
The default implementation of theme_file_icon now provides alt
text, and converts common file types to human readable text
(e.g. 'application/vnd.ms-powerpoint' => 'Office spreadsheet icon').
Unknown file types receive a generic "file icon".
Our version used the mime type for alt text, which was not very
useful.
> Remove ug_theme_file_icon.

- profiles/ug/modules/ug/ug_migrate_d6/migrate_settings_d6.php
- profiles/ug/modules/ug/ug_migrate_d6/ug_migrate_d6_node.inc
Fixes #373 
- Migrates img_assist tag files
- Replaces multiple img_assist tags in body field with <img> src
- Include prefix variables in migrate config file for page, news, event
> (UG Migrate D6) Replace img_assist with html in Page/Event/News (#373)

- profiles/ug/modules/ug/ug_migrate_d7/ug_migrate_d7_node.inc
Fixes #351 
Allows private files to be migrated.
> Fix: Allow private file migration in UGFile7 (UG Migrate D7)[fixes #351]

- profiles/ug/modules/ug/ug_migrate_d6/migrate_settings_d6.php
- profiles/ug/modules/ug/ug_migrate_d6/ug_migrate_d6.migrate.inc
- profiles/ug/modules/ug/ug_migrate_d6/ug_migrate_d6_node.inc
- profiles/ug/themes/ug/ug_cornerstone/css/style.css
Fixes #355.
Migrates Featured Item, Featured Item category/keyword from Drupal 6 to Drupal 7. Depends on https://github.com/ccswbs/hjckrrh/pull/344.
**Testing Notes**
- Recommend testing with data from CIO (eg. video)
- Compatible with Image Attach or Image Assist for featured item image
> (Migrate D6) Add Featured Item migration class + Featured Item category/keyword

- profiles/ug/modules/ug/ug_migrate_d7/ug_migrate_d7_node.inc
Fixes #415 
Uses Events, News, and FAQ keyword classes as an additional sourceMigration.
> Fix: Use keyword as sourceMigration for FAQ, News, Event (UG Migrate D7)[fix #415]

- profiles/ug/modules/ug/ug_migrate_d6/migrate_settings_d6.php
- profiles/ug/modules/ug/ug_migrate_d6/ug_migrate_d6.migrate.inc
- profiles/ug/modules/ug/ug_migrate_d6/ug_migrate_d6_node.inc
Fixes #355.
Migrates Featured Item, Featured Item category/keyword from Drupal 6 to Drupal 7. Depends on #344.
Testing Notes
Recommend testing with data from CIO (eg. video)
Compatible with Image Attach or Image Assist for featured item image
> Migrate featureditem d6

- profiles/ug/modules/ug/ug_page/ug_page.views_default.inc
When using the wildcard (e.g. pages/all/feed) set the title of the feed to
"Pages related to all".
> Fix: Override feed title when filter is "all" (ug_profile)[issue368]

- profiles/ug/CHANGELOG.txt
- profiles/ug/modules/ug/ug_event/ug_event.features.field_base.inc
- profiles/ug/modules/ug/ug_event/ug_event.features.field_instance.inc
- profiles/ug/modules/ug/ug_event/ug_event.info
- profiles/ug/modules/ug/ug_event/ug_event.test
- profiles/ug/modules/ug/ug_event/ug_event.views_default.inc
Fixes issue #87.
Changes event listing views to use the body summary or trimmed value, instead of the default body value.
HTML is stripped from the summary to prevent layout problems.
> Iss87 event listing summary

- profiles/ug/themes/ug/ug_theme/css/base.css
- profiles/ug/themes/ug/ug_theme/js/ug_scripts.js
- Wrap slide navigation indicators in div carousel-table for better positioning
- Make indicators larger and keyboard-accessible, with media query to shrink them slightly for small screens
- Use existing pagination styling for the indicators 
- Move the previous and next slide icons so they bookend the indicators
> Update base.css - add bootstrap carousel overrides

- profiles/ug/themes/ug/ug_theme/template.php
Fix issue #606.
Hid parent wrapper of problematic button using the class element-hidden which applies display:none. Bootstrap's hook_form_alter was overridden in the ug_theme to accomplish this.
> Fix issue606 - Hide button parent with display:none

- profiles/ug/modules/ug/ug_event/ug_event.test
- profiles/ug/themes/ug/ug_theme/templates/views-view-fields--e1.tpl.php
Fix for issue #587.
Added conditional to check for presence of the "Events related to ___" header and output the event titles as h3's if it is present. This was implemented because the template was already overridden and hard coded to output h2's for the individual event titles.
Unit test creates an event with a random name and tests the hierarchy with assert raw.
> Fix and unit test for issue587

- profiles/ug/modules/ug/ug_social/ug_social.features.inc
- profiles/ug/ug.info
Fix issue #548.
Removed 'print' as a dependency from ug.info and instead enabled it from hook_install in ug_social.features.inc.
> Issue #548 - Fix exceptions in tests caused by print module

- profiles/ug/modules/ug/ug_social/ug_social.features.inc
Issue #548.
Adding permissions to the social feature causes exceptions in tests because it adds the print module to the .info file as a dependency. Enable print permissions from hook_install and hook_update instead.
> Issue 548 - Add print permissions

- profiles/ug/themes/ug/ug_theme/css/base.css
Issue #485.
Links that are styled as headers (e.g. <a class="h2" href="#">Test</a>) will now appear blue with an underline. Previous behavior was for them to appear as normal headers with no indication they were clickable which is a failure according to the WCAG.
**Previous Behavior:**
**Expected Behavior:**
Note that the HTML has been edited through the inspector in both instances to see the effect.
> Issue 485 - Override header color with link color

- profiles/ug/themes/ug/ug_theme/css/base.css
Issue #615.
Changed font from default link color (#2F70A9) to black (#000000) which has a contrast ratio of 8.11 against the blue background of an all-day event (#74A5D7). Also changed the font size from "x-small" to "11px" as the next relative size up (small) was too large to look good.
The above was accomplished by overriding the calendar module's styles in our theme's base.css. Works for both E8b and E9b.
**Before/After:**
> Issue 615 - Change font size and color for all-day events

- profiles/ug/modules/ug/ug_profile/ug_profile.info
- profiles/ug/modules/ug/ug_profile/ug_profile.views_default.inc
Fixes Issue #650 
Exposed an existing filter on the PP5 view for last name search, added an exposed last name filter on PP1B (Notable Alumni)
- Checkout branch `iss650` look at the views changed to ensure change is as expected and fulfills the issue requirements.  
- Run the UG simpletest automated tests
> Issue 650 - Add last name search to PP views that are missing it

- profiles/ug/modules/ug/ug_event/ug_event.views_default.inc
Fixes #662.
Applied the same fix to E3 as to #593.
1. Create test event with start date in -1 day and end date in +1 day
2. Ensure test event shows up in `/events` under Upcoming Events
3. Ensure test event shows up in E3
4. Run UG Event automated tests
> Issue 662 - Change E3 filter from start date to end date

- profiles/ug/modules/ug/ug_course_outlines/ug_course_outlines.test
- profiles/ug/modules/ug/ug_course_outlines/ug_course_outlines.views_default.inc
Fixes #494 
Comment from @tqureshi-uog describing fix:
> @bdavey07 See attached code - it works by selectively rewriting and hiding results, i.e.
> **Section and term:** rewrite results of field with proper formatting, hide rewriting if empty
> **Instructor:** rewrite results `<p><strong>Instructor:</strong> [field_course_instructor]</p>`, hide rewriting if empty
> **Instructor, name only:** this is a plain text field (excluded from display, no rewriting) used for link text, token [field_course_instructor_1]
> **Instructor url:** No results text set to [field_course_instructor], hide if empty, hide rewriting if empty. Rewritten output is `<p><strong>Instructor:</strong> <a href="[field_course_instructor_url-url]"[field_course_instructor_1]</a></p>` (that is, if there's no value for …
> Issue 494 - Course Outlines detail page should hide field label if no associated content exists (eg. Term, Instructor)

- profiles/ug/modules/ug/ug_migrate_d6/migrate_settings_d6.php
- profiles/ug/modules/ug/ug_migrate_d6/ug_migrate_d6.migrate.inc
- profiles/ug/modules/ug/ug_migrate_d6/ug_migrate_d6_banner.inc
- profiles/ug/modules/ug/ug_migrate_d6/ug_migrate_d6_course.inc
- profiles/ug/modules/ug/ug_migrate_d6/ug_migrate_d6_node.inc
- profiles/ug/modules/ug/ug_migrate_d6/ug_migrate_d6_profile.inc
- profiles/ug/modules/ug/ug_migrate_d6/ug_migrate_d6_update.inc
- profiles/ug/modules/ug/ug_migrate_d7/migrate_settings_d7.php
- profiles/ug/modules/ug/ug_migrate_d7/ug_migrate_d7.migrate.inc
- profiles/ug/modules/ug/ug_migrate_d7/ug_migrate_d7_banner.inc
- profiles/ug/modules/ug/ug_migrate_d7/ug_migrate_d7_book.inc
- profiles/ug/modules/ug/ug_migrate_d7/ug_migrate_d7_course.inc
- profiles/ug/modules/ug/ug_migrate_d7/ug_migrate_d7_node.inc
- profiles/ug/modules/ug/ug_migrate_d7/ug_migrate_d7_update.inc
Fixes #539 
In order to migrate all formats as filtered_html (ie. override the source format), the person migrating can go into their site-specific migration configuration file and:
- set the variable "default_format" to the format they wish to migrate to (eg. filtered_html)
- set the variable "override_format" to TRUE
Default behaviour remains to migrate the source format to the destination format (so if half the items on the source site are filtered_html and half are full_html, you will find the same on the migrated destination site). This allows us to migrate sites with their format intact, rather than setting a format which could potentially strip content if people saved.
---
```
mysql> select body_format from field_data_body where bundle="article";
+---------------+
| body_format   | …
```
> Iss539 migrate format

- profiles/ug/modules/ug/ug_profile/ug_profile.features.field_base.inc
- profiles/ug/modules/ug/ug_profile/ug_profile.features.field_instance.inc
- profiles/ug/modules/ug/ug_profile/ug_profile.test
Fixes #628 
Updated People Profile so that multiple website links can be associated with one profile.
Label has been updated from "Website link" to "Website links".
Test creates a profile node with multiple website links, goes to profile page, checks for "Website links" label and confirms that both links exist on the profile page.
- Recommend adding multiple website links to a profile to check behaviour
- Recommend running UG Profile tests on Simpletest
> Iss628 profilelinks

- profiles/ug/themes/ug/ug_theme/css/base.css
Fixes the banner color contrast issue by removing the dark color from the `<p>` css rule rather than spot-fixing by overwriting the color in specific cases.
> Issue 752 - Banner color contrast

- profiles/ug/modules/ug/ug_social/ug_social.features.field_base.inc
Adds snapchat as an option under Social media network for UG Social. Because the icon is from a newer version of the Font Awesome library, the icon is not automatically included as part of the Font Awesome module that we have available.
For specific sites that want snapchat, to get the icon to show, you need to go under Configuration / Performance and ensure "Use CDN version of FontAwesome." is checked.
1. Go under Configuration / Performance and ensure "Use CDN version of FontAwesome." is checked.
2. Create a social media item and fill in any necessary information
3. Select Snapchat as the Social media network
4. Save the social media item
5. See if the icon shows and functions on the Follow Us (Icons + Text) viewpane and the Follow Us (Icons Only) viewpane.
----
**Note:** Going forward, …
> Add snapchat (UG Social)[fixes #528]

- profiles/ug/drupal-org.make
- profiles/ug/patches/services.patch
- sites/all/modules/services/resources/taxonomy_resource.inc
Replacing #775 as a cleaner solution that includes the Services 3.20 update (the referenced pull request uses Services 3.19).  
Changes the services module to return the value of the term ID rather than the success code.
> Patch for Services Module 3.20

- profiles/ug/themes/ug/ug_theme/template.php
**Issue:** Names in PP6 are having special characters escaped before they display which causes problems with names like O'Halloran:
The PP6 pre-process function in template.php was using the `l()` method to concatenate the first and last names and wrap them in an `<a>` tag. This method also seems to escape the contents, which is what's causing the problem.
1. Setup `/people` with a PP6 view
2. Add a profile that has a special character in either the first or last name fields
3. Ensure the special character is rendered correctly and not escaped
> [Next] Fix issue with certain characters being escaped in PP6 names

- profiles/ug/themes/ug/ug_cornerstone/templates/includes/ug-header.inc
This branch replaces the old logo with the new link. See before/after screenshots attached:
> Replace Old Cornerstone Logo

- profiles/ug/themes/ug/ug_cornerstone/css/ug2015-v1.css
- profiles/ug/themes/ug/ug_cornerstone/templates/includes/ug-header.inc
Removing the toolbar at the top caused the search bar to sit flush against the top of the page. I ended up adding a padding to the top of the `#ug-navbar` element to create a gap the same height as the toolbar. This padding doesn't move the logo because the logo is actually in a sibling container to the navigation.
> Remove toolbar and ensure nothing else in the header moves

- profiles/ug/themes/ug/ug_cornerstone/templates/page.tpl.php
- profiles/ug/themes/ug/ug_theme/templates/block.tpl.php
Fixes #791
Recreating #798 against master.
---
Replaced `<section>` tags in the block and page templates with `<div>` tags. Both are generic tags, but the latter does not implicitly gain the `role="region"` attribute.
1. Checkout `iss791` branch
2. Ctrl + F the inspector for section tags
3. Visually compare the site to a site running master to ensure no styles broke when the tags were changed
> [Master] Issue 791 - Siteimprove Issue: Naming Generic Landmarks

- profiles/ug/themes/ug/ug_cornerstone/css/ug2015-v1.css
- profiles/ug/themes/ug/ug_cornerstone/templates/page.tpl.php
Fixes ccswbs/hjckrrh#792
Settled on option (b) and modified the UG Cornerstone template to wrap the site title in an `<h1>` tag if it is showing the homepage. There were also some styles added in order to make the wrapped title look the same as other pages (may need to discuss where the styles were added).
1. Checkout `iss792`
2. Navigate to the homepage 
- Inspect the site title for an `<h1>` tag
- Ensure the site title visually matches other pages
3. Navigate to any other page on the site and ensure there is no `<h1>` tag around the site title
> [Master] Issue 792 - Change site title to h1 if on front page

- profiles/ug/themes/ug/ug_theme/template.php
**Issue:** Names in PP6 are having special characters escaped before they display which causes problems with names like O'Halloran:
The PP6 pre-process function in template.php was using the `l()` method to concatenate the first and last names and wrap them in an `<a>` tag. This method also seems to escape the contents, which is what's causing the problem.
1. Setup `/people` with a PP6 view
2. Add a profile that has a special character in either the first or last name fields
3. Ensure the special character is rendered correctly and not escaped
> [Master] Change to non-escaping method for printing name in PP6 fields template

- profiles/ug/themes/ug/ug_theme/css/base.css
Plus sign for when content is collapsed, minus sign for when it's expanded. The symbols come from Bootstrap Glyphicons
> Update base.css - add expand/collapse icons

- profiles/ug/themes/ug/ug_theme/template.php
- profiles/ug/themes/ug/ug_theme/templates/views-view-fields--pp6.tpl.php
This pull request updates the PP6 teaser template to display custom profile fields if they are present. The code in here is only half of the changes to be made, configuration changes will also have to be made on the view itself. Those changes are not included as this is pretty much an HR-specific fix for their "Leave for Change" fields, and allows for selective implementation.
Once this PR has been merged and the changes released, the following steps can be taken to display custom fields on the PP6 teaser view:
1. Add the "Content: Profile fields" field to the view (NOT the delta entry)
2. Configure the field:
- Remove all text from the Edit/Delete/Add link fields
- Multiple Field Settings: clear the "Separator" field
- Style Settings: check "Customize field HTML" and "Create a CSS Class" …
> TFS#845 - Display Custom Fields on PP6

- profiles/ug/themes/ug/ug_theme/css/features.css
These changes allow the Notable Alumni-style grid view to be used on images other than those for People Profiles. The classes require Full HTML access, but can be applied to basic page content via CKeditor (as opposed to Notable Alumni, which was generated by a View)
To test, copy the source code from here: https://dev.web.uoguelph.ca/tqdev/image-overlay
Experiment with different-sized images and broken images (i.e. to see if alt text shows up properly)
> CSS for img overlay

- profiles/ug/modules/ug/ug_search/ug_search.features.user_permission.inc
- profiles/ug/themes/ug/ug_theme/template.php
Test branch iss606-fix on Github.
**Check the following:**
- Search box (local) on Search Results page
- Search box (local) on general node pages
- Search box (local) anywhere else you can think of
**Ensure that:**
- Anything searched in the (local) search box gives out a result
- When you listen with a screen-reader, you only hear one "Search button" as opposed to two. Also ensure that you cannot tab to a second hidden Search button right after the first one.
- There is an explicit label (for - id) association for both the breadcrumb search box and on the search results page
> Fix broken search and hide duplicate search button [fixes #606]

- profiles/ug/themes/ug/ug_cornerstone/templates/html.tpl.php
- profiles/ug/themes/ug/ug_cornerstone/templates/includes/ug-footer.inc
- profiles/ug/themes/ug/ug_cornerstone/templates/includes/ug-header.inc
- profiles/ug/themes/ug/ug_cornerstone/templates/page--search.tpl.php
- profiles/ug/themes/ug/ug_cornerstone/templates/page.tpl.php
Fixes should:
- add skip link landmark
- update labels for landmarks
- remove Siteimprove warnings related to landmarks (see #510 )
When testing:
- check with Siteimprove
- check with HTML validator
- check with screen-reader
> Update landmarks / remove redundant WAI-ARIA labels (fixes #510)

- profiles/ug/modules/ug/ug_event/ug_event.features.field_instance.inc
- profiles/ug/modules/ug/ug_news/ug_news.features.field_instance.inc
- profiles/ug/modules/ug/ug_page/ug_page.features.field_instance.inc
Cherry-picked Joy's update on filetypes from branch iss767-update-fontawesome (see https://github.com/ccswbs/hjckrrh/pull/884).
> Add mp3, ogg to allowed file list: news, event, page

- profiles/ug/drupal-org.make
We're getting the following error when packaging fontawesome:
```
The library 'fontawesome' cannot be downloaded from                                             [error]
https://github.com/FortAwesome/Font-Awesome.git, the URL must be in the whitelist available at
https://www.drupal.org/packaging-whitelist.
The Drupal.org validation check failed -- see https://www.drupal.org/node/1432190 for more      [error]
information.
```
This removes the reference in the makefile so the validation check will pass.
> Remove Fontawesome library from makefile

- profiles/ug/modules/ug/ug_profile/ug_profile.views_default.inc
- profiles/ug/themes/ug/ug_theme/template.php
- profiles/ug/themes/ug/ug_theme/templates/views-view-fields--pp6.tpl.php
These changes are for the bioinformatics profile pages
- name should not be linked to drupal profile, if the nid field is not used.
- body and website fields should be below the name
> changed PP6 view to add body, website link, and remove link from name

- sites/all/libraries/tcpdf/images
Print module doesn't use images folder from tcpdf library, but we need this symlink to skip permissions check from drupal status page.
> Adding images symlink to fix tcpdf permission issue

- profiles/ug/modules/ug/ug_profile/ug_profile.views_default.inc
- profiles/ug/themes/ug/ug_theme/template.php
- profiles/ug/themes/ug/ug_theme/templates/views-view-fields--pp6.tpl.php
- Allows site managers to add keywords as a visible field on PP6 custom view using the in-place editor. 
- Displays websites on a single line on PP6 (to be consistent with the keyword display)
By default, the keyword field does not show, so existing sites should see no visible change from this update until the site manager adds the field. Once enabled, Keywords should appear below Office with a comma-separated field.
> Add keywords as optional field on PP6 custom view

- profiles/ug/drupal-org.make
- profiles/ug/modules/ug/ug_wysiwyg/ug_wysiwyg.features.ckeditor_profile.inc
- profiles/ug/modules/ug/ug_wysiwyg/ug_wysiwyg.features.filter.inc
- profiles/ug/modules/ug/ug_wysiwyg/ug_wysiwyg.features.inc
- profiles/ug/modules/ug/ug_wysiwyg/ug_wysiwyg.features.user_permission.inc
- profiles/ug/modules/ug/ug_wysiwyg/ug_wysiwyg.strongarm.inc
- sites/all/modules/ckeditor/CHANGELOG.txt
- sites/all/modules/ckeditor/ckeditor.config.js
- sites/all/modules/ckeditor/ckeditor.info
- sites/all/modules/ckeditor/ckeditor.module
- sites/all/modules/ckeditor/includes/ckeditor.admin.js
- sites/all/modules/ckeditor/includes/ckeditor.drush.inc
- sites/all/modules/ckeditor/includes/ckeditor.lib.inc
- sites/all/modules/ckeditor/includes/ckeditor.page.inc
- sites/all/modules/ckeditor/includes/ckeditor.user.inc
- sites/all/modules/ckeditor/includes/ckeditor.utils.js
- sites/all/modules/ckeditor/includes/jqueryUI/sort.js
Update the Drupal ckeditor module to 7.x-1.19 and update the ckeditor library to 4.14.0. This fixes [SA-CONTRIB-2020-007](https://www.drupal.org/sa-contrib-2020-007) and [SA-CORE-2020-001](https://www.drupal.org/sa-core-2020-001).
The previous default CKEditor skin (moono) has been replaced by a new skin (moono-lisa) which looks slightly different but has the same functionality. The ug_wysiwyg feature has been updated to use the new skin by default. Sites that override the ug_wysiwyg feature module will need to be updated to use the new default skin (manually or by reverting the ug_wysiwyg feature).
In the default configuration, the CKEditor library is loaded from the CDN. The previous version of the ug_wysiwyg feature referenced the 4.4.3 version of the library. The default configuration …
> Upgrade ckeditor module library (fixes SA-CONTRIB-2020-007)

- profiles/ug/themes/ug/ug_theme/css/base.css
- profiles/ug/themes/ug/ug_theme/css/layout.css
- Ensure linked headings use the standard blue link colour
- Ensure .lead class uses Bootstrap sizes
- Add responsive video embed classes
- Add spacer classes that allow users to assign padding and margins of 10px, 15px, 20px, and 40px. 
```
<div class="embed-responsive embed-responsive-16by9">
<iframe class="embed-responsive-item" src="..."></iframe>
</div>
<div class="embed-responsive embed-responsive-4by3">
<iframe class="embed-responsive-item" src="..."></iframe>
</div>
```
For the spacer classes, the naming format is {property}{sides}-{size}. 
Where {property} is one of:
- m - for classes that set margin
- p - for classes that set padding
Where {sides} is one of:
- t - for classes that set margin-top or padding-top
- b - for classes that set margin-bottom or padding-bottom
- l - for …
> Style updates

- profiles/ug/themes/ug/ug_cornerstone/templates/includes/ug-header.inc
- profiles/ug/themes/ug/ug_cornerstone/templates/page.tpl.php
UG global and local navigations are triggering an automatic failure on Microsoft Accessibility Insights. 
This PR fixes the issue by adding a navigation role to both elements.
> Add navigation role to ug and primary nav

- CHANGELOG.txt
- includes/bootstrap.inc
- includes/file.inc
- modules/system/system.module
"hotfix" release to address a PHP 5.x regression caused by SA-CORE-2023-005.
> Update to Drupal 7.97. For more information, see https://www.drupal.org/project/drupal/releases/7.97

- profiles/ug/drupal-org.make
- sites/all/modules/file_entity/file_entity.info
- sites/all/modules/file_entity/file_entity.pages.inc
- sites/all/modules/file_entity/tests/file_entity_test.info
Updated makefile, to set smtp to 1.9 (matches version already in modules dir)
Updated file_entity to 2.39
Removed feeds_ex from makefile
The directory changes were not committed for feeds_ex, and datalayer modules so they still exist in the modules dir.
> updated file entity to 2.39

- .github/update_tag1_d7es.sh
- .github/workflows/update_tag1_d7es.yml
- CHANGELOG.txt
- includes/bootstrap.inc
- includes/common.inc
- includes/errors.inc
- includes/mail.inc
- includes/utility.inc
- modules/field/modules/text/text.test
- modules/filter/filter.module
- modules/filter/filter.test
- modules/pantheon/tag1_d7es/LICENSE.txt
- modules/pantheon/tag1_d7es/README.md
- modules/pantheon/tag1_d7es/includes/uuid.inc
- modules/pantheon/tag1_d7es/tag1_d7es.info
- modules/pantheon/tag1_d7es/tag1_d7es.install
- modules/pantheon/tag1_d7es/tag1_d7es.module
- modules/path/path.module
- modules/simpletest/simpletest.pages.inc
- modules/simpletest/tests/bootstrap.test
- modules/simpletest/tests/cache.test
- modules/simpletest/tests/error.test
- modules/simpletest/tests/password.test
- modules/simpletest/tests/session.test
- modules/system/system.install
- modules/system/system.mail.inc
- modules/system/system.test
- profiles/ug/ug.install
- sites/default/default.settings.php
- Add core updates from Pantheon that include D7 longterm support
- Add update hook that enables tag1_d7es module
- Use site_mail as email address to notify when module updates go out
> Add Drupal Longterm Support module via Pantheon

- .github/update_tag1_d7es.sh
Update Github Action so it can automatically create PRs for our custom upstream when the tag1_d7es module gets updated.
> Adapt update_tag1_d7es workflow
