profiles/ug/themes/ug/ug_theme/template.php
modified the "more" link for the view, to show either /pages or /pages/category/#
=> Pg3 page item more link

profiles/ug/modules/ug/ug_migrate_d7/migrate_settings_d7.php, profiles/ug/modules/ug/ug_migrate_d7/ug_migrate_d7.migrate.inc, profiles/ug/modules/ug/ug_migrate_d7/ug_migrate_d7_node.inc, sites/all/modules/field_collection/field_collection.module
This branch builds off https://github.com/ccswbs/hjckrrh/pull/341. (It requires UGFile7 which is included in that branch.)
Adds feature image to UG Migrate D7. Tested successfully on News feature image using Business. Recommend testing the events feature image migration with DHR.
=> (Migrate D7) Add Feature Image migration to News, Event

profiles/ug/modules/ug/ug_migrate_d7/migrate_settings_d7.php, profiles/ug/modules/ug/ug_migrate_d7/ug_migrate_d7.migrate.inc, profiles/ug/modules/ug/ug_migrate_d7/ug_migrate_d7_node.inc
Implements FAQ, FAQ category, and FAQ term migrations from Drupal 7 to Drupal 7.
Fixes #357
=> Migrate faq d7 (Issue #357)

profiles/ug/modules/ug/ug_news/ug_news.info, profiles/ug/modules/ug/ug_news/ug_news.test
Add a test case for UG News and a test for "More news" link behaviour.
=> New: Add UG News test case (ug_news)

profiles/ug/modules/ug/ug_migrate_d6/ug_migrate_d6_user.inc
Fixes #383 
Preserves User 1 during group update / rollback.
=> (UG Migrate D6) Fix: Preserve User 1 during group update/rollback [fixes 383]

profiles/ug/modules/ug/ug_migrate_d7/ug_migrate_d7.migrate.inc, profiles/ug/modules/ug/ug_migrate_d7/ug_migrate_d7_node.inc
Fixes #413 
Adds featured item keyword migration.
=> New: Add Featured Item keyword migration (UG Migrate D7)[fix #413]

profiles/ug/modules/ug/ug_migrate_d7/ug_migrate_d7.migrate.inc, profiles/ug/modules/ug/ug_migrate_d7/ug_migrate_d7_node.inc
=> New: Add keyword migration for Page (UG Migrate D7)[fix #416]

profiles/ug/modules/ug/ug_migrate_d7/migrate_settings_d7.php, profiles/ug/modules/ug/ug_migrate_d7/ug_migrate_d7.migrate.inc, profiles/ug/modules/ug/ug_migrate_d7/ug_migrate_d7_node.inc
Adds keyword migration for Profile.
(Note: Indented the profile node migration class for consistency, so it will look like a lot of lines changed...)
=> (UG Migrate D7) Adds keyword migration for Profile [fix #419]

profiles/ug/modules/ug/ug_page/ug_page.views_default.inc, profiles/ug/themes/ug/ug_theme/template.php, profiles/ug/themes/ug/ug_theme/templates/views-view-fields--n3-summary.tpl.php
=> [issue#266] Ability to choose to include Summary in News Teaser list view [resolves #266]

profiles/ug/themes/ug/ug_cornerstone/templates/includes/ug-footer.inc
needs testing using a screenreader.
=> [issue435] Fix: added screen reader text for uofg footer links [resolves #435]

profiles/ug/themes/ug/ug_theme/templates/views-view-fields--s1.tpl.php
Need to login to a Linkedin account to test the functionality.
=> modified the linkedin link to set the URL field correctly

profiles/ug/CHANGELOG.txt, profiles/ug/modules/ug/ug_course_outlines/ug_course_outlines.views_default.inc, profiles/ug/themes/ug/ug_theme/template.php
=> Show active menu item when filtering course outlines by term (#499)

profiles/ug/modules/ug/ug_migrate_d7/migrate_settings_d7.php
Update documentation for UG Migrate D7 about how to map custom text fields into body field.
=> Docs: Add instructions for custom fields mapped into body (UG Migrate D7)

profiles/ug/themes/ug/ug_theme/css/base.css
=> remove a:focus outline rule

profiles/ug/modules/ug/ug_permit/ug_permit.module
=> Fix: Integrity constraint violation in ug_permit (#551)

profiles/ug/modules/ug/ug_theme_settings/ug_theme_settings.test, profiles/ug/themes/ug/ug_cornerstone/templates/includes/ug-header.inc
=> Updated Distance Education link

profiles/ug/modules/ug/ug_event/ug_event.views_default.inc, profiles/ug/modules/ug/ug_feature/ug_feature.features.field_base.inc, profiles/ug/modules/ug/ug_feature/ug_feature.features.field_instance.inc, profiles/ug/modules/ug/ug_feature/ug_feature.views_default.inc, profiles/ug/modules/ug/ug_news/ug_news.views_default.inc
=> Override feed title with category if present

profiles/ug/modules/ug/ug_social/ug_social.views_default.inc, profiles/ug/themes/ug/ug_theme/template.php, profiles/ug/themes/ug/ug_theme/templates/views-more.tpl.php, profiles/ug/themes/ug/ug_theme/templates/views-view.tpl.php
=> Fix: Style RSS feed icon (#394)

profiles/ug/modules/ug/ug_wysiwyg/ug_wysiwyg.strongarm.inc
=> Fix: Update CkEditor Link configuration so it can search for Book pages

profiles/ug/modules/ug/ug_migrate_d7/migrate_settings_d7.php, profiles/ug/modules/ug/ug_migrate_d7/ug_migrate_d7.migrate.inc, profiles/ug/modules/ug/ug_migrate_d7/ug_migrate_d7_book.inc
Migrate book attachments, keywords, category / Add UpdateBook class
=> Issue562 564 - Migrate book attachments, keywords, category / Add UpdateBook class (UG Migrate D7)

profiles/ug/modules/ug/ug_profile/ug_profile.test, profiles/ug/modules/ug/ug_profile/ug_profile.views_default.inc, profiles/ug/modules/ug/ug_profile_layouts/ug_profile_layouts.info, profiles/ug/modules/ug/ug_profile_layouts/ug_profile_layouts.pages_default.inc
Issue #595 
Added tag argument to PP1 and included automated test.
=> Iss595 pp1 tag

profiles/ug/themes/ug/ug_theme/css/base.css
=> Issue 608 - In-place editor overflows

profiles/ug/modules/ug/ug_profile/ug_profile.views_default.inc
Hides empty fields on PP1: No Pictures.
=> Fix empty fields not hidden

profiles/ug/themes/ug/ug_theme/css/base.css
Reverts ccswbs/hjckrrh#638 - more changes required
=> Revert "Issue 485 - Override header color with link color"

profiles/ug/modules/ug/ug_event/ug_event.test, profiles/ug/modules/ug/ug_event/ug_event.views_default.inc
=> Issue 593 - Long events

profiles/ug/modules/ug/ug_path_breadcrumbs/ug_path_breadcrumbs.info, profiles/ug/modules/ug/ug_path_breadcrumbs/ug_path_breadcrumbs.path_breadcrumbs.inc
=> Issue 643 - Remove node:title from breadcrumb

profiles/ug/drupal-org.make, sites/all/modules/media/includes/MediaEntityTranslationHandler.inc, sites/all/modules/media/includes/media.fields.inc, sites/all/modules/media/includes/media.pages.inc, sites/all/modules/media/media.info, sites/all/modules/media/media.install, sites/all/modules/media/media.module, sites/all/modules/media/media.views.inc, sites/all/modules/media/modules/media_bulk_upload/media_bulk_upload.info, sites/all/modules/media/modules/media_internet/media_internet.info, sites/all/modules/media/modules/media_internet/tests/media_internet_test.info, sites/all/modules/media/modules/media_migrate_file_types/media_migrate_file_types.info, sites/all/modules/media/modules/media_wysiwyg/css/media_wysiwyg.base.css, sites/all/modules/media/modules/media_wysiwyg/css/media_wysiwyg.css, sites/all/modules/media/modules/media_wysiwyg/includes/media_wysiwyg.filter.inc, sites/all/modules/media/modules/media_wysiwyg/includes/media_wysiwyg.pages.inc, sites/all/modules/media/modules/media_wysiwyg/js/media_wysiwyg.filter.js, sites/all/modules/media/modules/media_wysiwyg/media_wysiwyg.info, sites/all/modules/media/modules/media_wysiwyg/media_wysiwyg.install, sites/all/modules/media/modules/media_wysiwyg/media_wysiwyg.module, sites/all/modules/media/modules/media_wysiwyg/wysiwyg_plugins/media.inc, sites/all/modules/media/modules/media_wysiwyg_view_mode/media_wysiwyg_view_mode.info, sites/all/modules/media/modules/mediafield/mediafield.info, sites/all/modules/media/tests/media.test, sites/all/modules/media/tests/media_module_test.info
- Updated makefile to include media module v2.0.
- Checked in the upgraded media module files
=> Upgrade media module to 2.0

profiles/ug/themes/ug/ug_cornerstone/templates/html.tpl.php, profiles/ug/themes/ug/ug_theme/js/ug_scripts.js, profiles/ug/themes/ug/ug_theme/ug_theme.info
For #732 - Adding the noscript fix so bootstrap elements with collapse class expand by default if javascript disabled
=> Bootstrap collapsible elements do not degrade gracefully

profiles/ug/modules/ug/ug_page/ug_page.info
Fixes issue #602 
1. Clone hjckrrh repo
2. Checkout iss602
3. Run automated tests
I was able to run all the UG automated tests with no errors.  Reviewers should be able to run tests with no errors as well.
=> Removed dependancy on UG Page Layout from UG Page

profiles/ug/drupal-org.make, sites/all/modules/mpac/LICENSE.txt, sites/all/modules/mpac/README.txt, sites/all/modules/mpac/mpac.admin.inc, sites/all/modules/mpac/mpac.info, sites/all/modules/mpac/mpac.module
Fixes #674.
1. Checkout branch `iss674`
2. Run `drush make --no-core profiles/ug/drupal-org.make`, modify the path to the makefile according to your current working directory
3. Ensure the make command runs without errors
4. Check that the Multi Path Autocomplete module is present but disabled on your site
=> Issue 674 - Add MPAC module to repo

profiles/ug/drupal-org.make, profiles/ug/patches/services.patch, sites/all/modules/services/resources/taxonomy_resource.inc
Replacing #775 as a cleaner solution that includes the Services 3.20 update (the referenced pull request uses Services 3.19).
=> Patch for Services Module 3.20

profiles/ug/modules/ug/ug_profile/ug_profile.features.field_instance.inc
Fixes ccswbs/hjckrrh#776
Enables description field on People Profile attachments.
=> [Next] Enable Description Field on People Profiles

profiles/ug/modules/ug/ug_profile/ug_profile.features.field_instance.inc
Fixes ccswbs/hjckrrh#776
Enables description field on People Profile attachments.
=> [Master] Enable description field for People Profiles

profiles/ug/modules/ug/ug_profile/ug_profile.info, profiles/ug/modules/ug/ug_profile/ug_profile.views_default.inc, profiles/ug/themes/ug/ug_theme/template.php, profiles/ug/themes/ug/ug_theme/templates/views-view-fields--pp6.tpl.php
This pull request updates PP6 to visually match PP1. The specific changes include adding Bootstrap's "img-rounded" class to images by setting their display type and adding the field_profile_title field to the teaser display.
=> Issue 830 - Fix PP6 to match PP1

profiles/ug/modules/ug/ug_profile/ug_profile.info, profiles/ug/modules/ug/ug_profile/ug_profile.views_default.inc
FIxes #816
Recreating #818 against master.
=> [Master] Issue 816 - Add empty alt attribute to profile images on PP1B view

sites/all/modules/backup_migrate/README.txt, sites/all/modules/backup_migrate/backup_migrate.info, sites/all/modules/backup_migrate/backup_migrate.install, sites/all/modules/backup_migrate/backup_migrate.module, sites/all/modules/backup_migrate/includes/backup_migrate.drush.inc, sites/all/modules/backup_migrate/includes/crud.inc, sites/all/modules/backup_migrate/includes/destinations.db.inc, sites/all/modules/backup_migrate/includes/destinations.db.mysql.inc, sites/all/modules/backup_migrate/includes/destinations.email.inc, sites/all/modules/backup_migrate/includes/destinations.file.inc, sites/all/modules/backup_migrate/includes/destinations.inc, sites/all/modules/backup_migrate/includes/destinations.nodesquirrel.inc, sites/all/modules/backup_migrate/includes/files.inc, sites/all/modules/backup_migrate/includes/filters.backup_restore.inc, sites/all/modules/backup_migrate/includes/filters.inc, sites/all/modules/backup_migrate/includes/filters.statusnotify.inc, sites/all/modules/backup_migrate/includes/locations.inc, sites/all/modules/backup_migrate/includes/profiles.inc, sites/all/modules/backup_migrate/includes/schedules.inc, sites/all/modules/backup_migrate/includes/sources.archivesource.inc, sites/all/modules/backup_migrate/includes/sources.db.inc, sites/all/modules/backup_migrate/includes/sources.db.mysql.inc, sites/all/modules/backup_migrate/includes/sources.filesource.inc, sites/all/modules/backup_migrate/tests/BackupMigrateBasicsTest.test, sites/all/modules/backup_migrate/tests/BackupMigrateHelper.test
This update addresses the following security update in the Backup and Migrate module:
https://www.drupal.org/sa-contrib-2018-004
Backup and Migrate module v7.x-3.4.
=> Update to Backup and Migrate module.

profiles/ug/drupal-org.make, profiles/ug/modules/ug/ug_profile_layouts/ug_profile_layouts.info, profiles/ug/modules/ug/ug_profile_layouts/ug_profile_layouts.pages_default.inc, profiles/ug/themes/ug/ug_theme/template.php, sites/all/modules/field_collection_bootstrap/field_collection_bootstrap.info, sites/all/modules/field_collection_bootstrap/field_collection_bootstrap.module, sites/all/modules/field_collection_tabs/LICENSE.txt, sites/all/modules/field_collection_tabs/field_collection_tabs.info, sites/all/modules/field_collection_tabs/field_collection_tabs.js, sites/all/modules/field_collection_tabs/field_collection_tabs.module
Displays profile sections as Bootstrap tabs.
=> Profile tabs

profiles/ug/modules/ug/ug_wysiwyg/ug_wysiwyg.info, profiles/ug/modules/ug/ug_wysiwyg/ug_wysiwyg.strongarm.inc, profiles/ug/ug.info
create delete imce_dir browser
=> Feature imce dir

profiles/ug/themes/ug/ug_cornerstone/css/style.css, profiles/ug/themes/ug/ug_theme/css/features.css
for UofG logo image and slider buttons
=> Iss865 visiblefocus

profiles/ug/themes/ug/ug_cornerstone/templates/includes/ug-header.inc
Update global header to:
- remove College of Business and Economics --> /business
- include Gordon S. Lang School of Business & Economics --> /lang
- ensure alphabetical order (see news.uoguelph.ca)
=> Add /lang to global header

profiles/ug/themes/ug/ug_theme/template.php
Added logic to check if the variable override_title exists.
=> Bug 4605: Override_title exists check fix

profiles/ug/themes/ug/ug_theme/css/base.css
To test, create a multidev based on the OAC site, pull the changes, and view this page in MS Edge: https://www.uoguelph.ca/oac/future-students/day-life-sara-stricker-msc-student - the misaligned pagination indicators that show on the live version should be fixed.
=> Update MS Edge media query detection method

profiles/ug/themes/ug/ug_cornerstone/css/ug2015-v1.css
Enforce .h1 through .h6 sizes on detail-page
=> Enforce .h1 through .h6 sizes on detail-page

CHANGELOG.txt, includes/bootstrap.inc, includes/file.inc, modules/image/image.module, modules/system/system.module, sites/default/default.settings.php
=> Update to Drupal 7.96

sites/default/ug.settings.php
Remove food-science-booking from upstream (it's not using the upstream)
=> Remove food-science-booking from upstream

pantheon.upstream.yml, pantheon.yml
downgrade to php 7.2 to fix issue with the last drupal core update
=> downgrade to php 7.2 to fix issue with the last drupal core update

profiles/ug/themes/ug/ug_theme/css/base.css
=> Update font fallbacks

pantheon.upstream.yml, pantheon.yml
Switch to using Drush 8 in the hjckrrh upstream.
=> Switch to using Drush 8
